type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type BingoCard @table {
  user: User!
  title: String!
  createdAt: Timestamp!
  theme: String
}

type CardItem @table {
  bingoCard: BingoCard!
  text: String!
  position: Int!
}

type GameSession @table {
  host: User!
  name: String!
  createdAt: Timestamp!
  status: String!
  password: String
}

type SessionPlayer @table {
  gameSession: GameSession!
  user: User!
  bingoCard: BingoCard!
  joinedAt: Timestamp!
  isBingoClaimed: Boolean
  claimedAt: Timestamp
}

type CalledItem @table {
  gameSession: GameSession!
  cardItem: CardItem!
  calledAt: Timestamp!
}